package com.jrdevel.aboutus.model;

// Generated 13/Nov/2013 22:02:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Church generated by hbm2java
 */
@Entity
@Table(name = "tbl_churchs")
public class Church implements java.io.Serializable {

	private Integer id;
	private File file;
	private String name;
	private String completeName;
	private String address;
	private String state;
	private String country;
	private String postalCode;
	private int nif;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<User> users = new HashSet<User>(0);

	public Church() {
	}

	public Church(String name, String completeName, int nif) {
		this.name = name;
		this.completeName = completeName;
		this.nif = nif;
	}

	public Church(File file, String name, String completeName, String address,
			String state, String country, String postalCode, int nif,
			Set<Person> persons, Set<User> users) {
		this.file = file;
		this.name = name;
		this.completeName = completeName;
		this.address = address;
		this.state = state;
		this.country = country;
		this.postalCode = postalCode;
		this.nif = nif;
		this.persons = persons;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logo")
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "completeName", nullable = false)
	public String getCompleteName() {
		return this.completeName;
	}

	public void setCompleteName(String completeName) {
		this.completeName = completeName;
	}

	@Column(name = "address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "postalCode", length = 100)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "nif", nullable = false)
	public int getNif() {
		return this.nif;
	}

	public void setNif(int nif) {
		this.nif = nif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "church")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "church")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
