package com.jrdevel.aboutus.model;

// Generated 15/Nov/2013 19:04:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer")
public class Customer implements java.io.Serializable {

	private Integer id;
	private Plan plan;
	private String name;
	private Set<Church> churches = new HashSet<Church>(0);
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<User> users = new HashSet<User>(0);

	public Customer() {
	}

	public Customer(Plan plan, String name) {
		this.plan = plan;
		this.name = name;
	}

	public Customer(Plan plan, String name, Set<Church> churches,
			Set<Person> persons, Set<User> users) {
		this.plan = plan;
		this.name = name;
		this.churches = churches;
		this.persons = persons;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Church> getChurches() {
		return this.churches;
	}

	public void setChurches(Set<Church> churches) {
		this.churches = churches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
