package com.jrdevel.aboutus.model;

// Generated 13/Nov/2013 22:02:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer plan;
	private Set<User> users = new HashSet<User>(0);

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

	public Customer(String name, Integer plan, Set<User> users) {
		this.name = name;
		this.plan = plan;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "plan")
	public Integer getPlan() {
		return this.plan;
	}

	public void setPlan(Integer plan) {
		this.plan = plan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
