package com.jrdevel.aboutus.model;

// Generated 23/Set/2013 20:26:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblGroupTblPermissionId generated by hbm2java
 */
@Embeddable
public class TblGroupTblPermissionId implements java.io.Serializable {

	private int tblGroupId;
	private int permissionsId;

	public TblGroupTblPermissionId() {
	}

	public TblGroupTblPermissionId(int tblGroupId, int permissionsId) {
		this.tblGroupId = tblGroupId;
		this.permissionsId = permissionsId;
	}

	@Column(name = "tbl_group_id", nullable = false)
	public int getTblGroupId() {
		return this.tblGroupId;
	}

	public void setTblGroupId(int tblGroupId) {
		this.tblGroupId = tblGroupId;
	}

	@Column(name = "permissions_id", nullable = false)
	public int getPermissionsId() {
		return this.permissionsId;
	}

	public void setPermissionsId(int permissionsId) {
		this.permissionsId = permissionsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblGroupTblPermissionId))
			return false;
		TblGroupTblPermissionId castOther = (TblGroupTblPermissionId) other;

		return (this.getTblGroupId() == castOther.getTblGroupId())
				&& (this.getPermissionsId() == castOther.getPermissionsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTblGroupId();
		result = 37 * result + this.getPermissionsId();
		return result;
	}

}
