package com.jrdevel.aboutus.model;

// Generated 23/Set/2013 20:26:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblPermissionTblGroupId generated by hbm2java
 */
@Embeddable
public class TblPermissionTblGroupId implements java.io.Serializable {

	private int tblPermissionId;
	private int groupsId;

	public TblPermissionTblGroupId() {
	}

	public TblPermissionTblGroupId(int tblPermissionId, int groupsId) {
		this.tblPermissionId = tblPermissionId;
		this.groupsId = groupsId;
	}

	@Column(name = "tbl_permission_id", nullable = false)
	public int getTblPermissionId() {
		return this.tblPermissionId;
	}

	public void setTblPermissionId(int tblPermissionId) {
		this.tblPermissionId = tblPermissionId;
	}

	@Column(name = "groups_id", nullable = false)
	public int getGroupsId() {
		return this.groupsId;
	}

	public void setGroupsId(int groupsId) {
		this.groupsId = groupsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPermissionTblGroupId))
			return false;
		TblPermissionTblGroupId castOther = (TblPermissionTblGroupId) other;

		return (this.getTblPermissionId() == castOther.getTblPermissionId())
				&& (this.getGroupsId() == castOther.getGroupsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTblPermissionId();
		result = 37 * result + this.getGroupsId();
		return result;
	}

}
